# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bilibili.app.view.v1 import view_pb2 as bilibili_dot_app_dot_view_dot_v1_dot_view__pb2

GRPC_GENERATED_VERSION = '1.82.0rc2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bilibili/app/view/v1/view_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ViewStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.View = channel.unary_unary(
                '/bilibili.app.view.v1.View/View',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewReply.FromString,
                _registered_method=True)
        self.ViewTag = channel.unary_unary(
                '/bilibili.app.view.v1.View/ViewTag',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewTagReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewTagReply.FromString,
                _registered_method=True)
        self.ViewMaterial = channel.unary_unary(
                '/bilibili.app.view.v1.View/ViewMaterial',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewMaterialReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewMaterialReply.FromString,
                _registered_method=True)
        self.ViewProgress = channel.unary_unary(
                '/bilibili.app.view.v1.View/ViewProgress',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewProgressReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewProgressReply.FromString,
                _registered_method=True)
        self.ShortFormVideoDownload = channel.unary_unary(
                '/bilibili.app.view.v1.View/ShortFormVideoDownload',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ShortFormVideoDownloadReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ShortFormVideoDownloadReply.FromString,
                _registered_method=True)
        self.ClickPlayerCard = channel.unary_unary(
                '/bilibili.app.view.v1.View/ClickPlayerCard',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ClickPlayerCardReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
                _registered_method=True)
        self.ClickActivitySeason = channel.unary_unary(
                '/bilibili.app.view.v1.View/ClickActivitySeason',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ClickActivitySeasonReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
                _registered_method=True)
        self.Season = channel.unary_unary(
                '/bilibili.app.view.v1.View/Season',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonReply.FromString,
                _registered_method=True)
        self.ExposePlayerCard = channel.unary_unary(
                '/bilibili.app.view.v1.View/ExposePlayerCard',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ExposePlayerCardReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
                _registered_method=True)
        self.AddContract = channel.unary_unary(
                '/bilibili.app.view.v1.View/AddContract',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.AddContractReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
                _registered_method=True)
        self.ChronosPkg = channel.unary_unary(
                '/bilibili.app.view.v1.View/ChronosPkg',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ChronosPkgReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.Chronos.FromString,
                _registered_method=True)
        self.CacheView = channel.unary_unary(
                '/bilibili.app.view.v1.View/CacheView',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.CacheViewReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.CacheViewReply.FromString,
                _registered_method=True)
        self.ContinuousPlay = channel.unary_unary(
                '/bilibili.app.view.v1.View/ContinuousPlay',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ContinuousPlayReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ContinuousPlayReply.FromString,
                _registered_method=True)
        self.RelatesFeed = channel.unary_unary(
                '/bilibili.app.view.v1.View/RelatesFeed',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.RelatesFeedReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.RelatesFeedReply.FromString,
                _registered_method=True)
        self.PremiereArchive = channel.unary_unary(
                '/bilibili.app.view.v1.View/PremiereArchive',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PremiereArchiveReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PremiereArchiveReply.FromString,
                _registered_method=True)
        self.Reserve = channel.unary_unary(
                '/bilibili.app.view.v1.View/Reserve',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ReserveReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ReserveReply.FromString,
                _registered_method=True)
        self.PlayerRelates = channel.unary_unary(
                '/bilibili.app.view.v1.View/PlayerRelates',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PlayerRelatesReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PlayerRelatesReply.FromString,
                _registered_method=True)
        self.SeasonActivityRecord = channel.unary_unary(
                '/bilibili.app.view.v1.View/SeasonActivityRecord',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonActivityRecordReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonActivityRecordReply.FromString,
                _registered_method=True)
        self.SeasonWidgetExpose = channel.unary_unary(
                '/bilibili.app.view.v1.View/SeasonWidgetExpose',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonWidgetExposeReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonWidgetExposeReply.FromString,
                _registered_method=True)
        self.GetArcsPlayer = channel.unary_unary(
                '/bilibili.app.view.v1.View/GetArcsPlayer',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetArcsPlayerReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetArcsPlayerReply.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/bilibili.app.view.v1.View/GetUser',
                request_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetUserReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetUserReply.FromString,
                _registered_method=True)


class ViewServicer:
    """Missing associated documentation comment in .proto file."""

    def View(self, request, context):
        """视频页详情页
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewTag(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewMaterial(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewProgress(self, request, context):
        """视频播放过程中的数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShortFormVideoDownload(self, request, context):
        """短视频下载
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickPlayerCard(self, request, context):
        """点击播放器卡片事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickActivitySeason(self, request, context):
        """点击大型活动页预约
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Season(self, request, context):
        """合集详情页
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExposePlayerCard(self, request, context):
        """播放器卡片曝光
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddContract(self, request, context):
        """点击签订契约
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChronosPkg(self, request, context):
        """资源包
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CacheView(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContinuousPlay(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RelatesFeed(self, request, context):
        """播放页推荐IFS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PremiereArchive(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reserve(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayerRelates(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeasonActivityRecord(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeasonWidgetExpose(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArcsPlayer(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'View': grpc.unary_unary_rpc_method_handler(
                    servicer.View,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewReply.SerializeToString,
            ),
            'ViewTag': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewTag,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewTagReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewTagReply.SerializeToString,
            ),
            'ViewMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewMaterial,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewMaterialReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewMaterialReply.SerializeToString,
            ),
            'ViewProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewProgress,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewProgressReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewProgressReply.SerializeToString,
            ),
            'ShortFormVideoDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.ShortFormVideoDownload,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ShortFormVideoDownloadReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ShortFormVideoDownloadReply.SerializeToString,
            ),
            'ClickPlayerCard': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickPlayerCard,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ClickPlayerCardReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.SerializeToString,
            ),
            'ClickActivitySeason': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickActivitySeason,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ClickActivitySeasonReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.SerializeToString,
            ),
            'Season': grpc.unary_unary_rpc_method_handler(
                    servicer.Season,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonReply.SerializeToString,
            ),
            'ExposePlayerCard': grpc.unary_unary_rpc_method_handler(
                    servicer.ExposePlayerCard,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ExposePlayerCardReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.SerializeToString,
            ),
            'AddContract': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContract,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.AddContractReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.SerializeToString,
            ),
            'ChronosPkg': grpc.unary_unary_rpc_method_handler(
                    servicer.ChronosPkg,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ChronosPkgReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.Chronos.SerializeToString,
            ),
            'CacheView': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheView,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.CacheViewReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.CacheViewReply.SerializeToString,
            ),
            'ContinuousPlay': grpc.unary_unary_rpc_method_handler(
                    servicer.ContinuousPlay,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ContinuousPlayReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ContinuousPlayReply.SerializeToString,
            ),
            'RelatesFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.RelatesFeed,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.RelatesFeedReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.RelatesFeedReply.SerializeToString,
            ),
            'PremiereArchive': grpc.unary_unary_rpc_method_handler(
                    servicer.PremiereArchive,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PremiereArchiveReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PremiereArchiveReply.SerializeToString,
            ),
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ReserveReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ReserveReply.SerializeToString,
            ),
            'PlayerRelates': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayerRelates,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PlayerRelatesReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PlayerRelatesReply.SerializeToString,
            ),
            'SeasonActivityRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.SeasonActivityRecord,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonActivityRecordReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonActivityRecordReply.SerializeToString,
            ),
            'SeasonWidgetExpose': grpc.unary_unary_rpc_method_handler(
                    servicer.SeasonWidgetExpose,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonWidgetExposeReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonWidgetExposeReply.SerializeToString,
            ),
            'GetArcsPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArcsPlayer,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetArcsPlayerReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetArcsPlayerReply.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetUserReq.FromString,
                    response_serializer=bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetUserReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.app.view.v1.View', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilibili.app.view.v1.View', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class View:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def View(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/View',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ViewTag',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewTagReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewTagReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ViewMaterial',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewMaterialReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewMaterialReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ViewProgress',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewProgressReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ViewProgressReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShortFormVideoDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ShortFormVideoDownload',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ShortFormVideoDownloadReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ShortFormVideoDownloadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickPlayerCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ClickPlayerCard',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ClickPlayerCardReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickActivitySeason(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ClickActivitySeason',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ClickActivitySeasonReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Season(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/Season',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExposePlayerCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ExposePlayerCard',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ExposePlayerCardReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/AddContract',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.AddContractReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.NoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChronosPkg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ChronosPkg',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ChronosPkgReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.Chronos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CacheView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/CacheView',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.CacheViewReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.CacheViewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContinuousPlay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/ContinuousPlay',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ContinuousPlayReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ContinuousPlayReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RelatesFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/RelatesFeed',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.RelatesFeedReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.RelatesFeedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PremiereArchive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/PremiereArchive',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PremiereArchiveReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PremiereArchiveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/Reserve',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ReserveReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.ReserveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayerRelates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/PlayerRelates',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PlayerRelatesReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.PlayerRelatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeasonActivityRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/SeasonActivityRecord',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonActivityRecordReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonActivityRecordReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeasonWidgetExpose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/SeasonWidgetExpose',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonWidgetExposeReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.SeasonWidgetExposeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArcsPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/GetArcsPlayer',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetArcsPlayerReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetArcsPlayerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.view.v1.View/GetUser',
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetUserReq.SerializeToString,
            bilibili_dot_app_dot_view_dot_v1_dot_view__pb2.GetUserReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
