"""init base stamp

Revision ID: f99b8f0891ed
Revises: 
Create Date: 2026-07-07 14:56:43.471038

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'f99b8f0891ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxy_tab', 'status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('proxy_tab', 'success_times',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('proxy_tab', 'zhihu_status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxy_tab', 'zhihu_status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('proxy_tab', 'success_times',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('proxy_tab', 'status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
