# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/community/service/cert/v1/cert.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bilibili/community/service/cert/v1/cert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-bilibili/community/service/cert/v1/cert.proto\x12\"bilibili.community.service.cert.v1\"5\n\x15\x46ieldCertPopActionReq\x12\x0c\n\x04\x61vid\x18\x01 \x01(\x03\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\"\x17\n\x15\x46ieldCertPopActionRsp\"%\n\x15\x46ieldCertPopRecordReq\x12\x0c\n\x04\x61vid\x18\x01 \x01(\x03\"\x17\n\x15\x46ieldCertPopRecordRspB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.community.service.cert.v1.cert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_FIELDCERTPOPACTIONREQ']._serialized_start=85
  _globals['_FIELDCERTPOPACTIONREQ']._serialized_end=138
  _globals['_FIELDCERTPOPACTIONRSP']._serialized_start=140
  _globals['_FIELDCERTPOPACTIONRSP']._serialized_end=163
  _globals['_FIELDCERTPOPRECORDREQ']._serialized_start=165
  _globals['_FIELDCERTPOPRECORDREQ']._serialized_end=202
  _globals['_FIELDCERTPOPRECORDRSP']._serialized_start=204
  _globals['_FIELDCERTPOPRECORDRSP']._serialized_end=227
# @@protoc_insertion_point(module_scope)
