# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bilibili.gaia.gw import gw_api_pb2 as bilibili_dot_gaia_dot_gw_dot_gw__api__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.82.0rc2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bilibili/gaia/gw/gw_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GaiaStub:
    """应用列表上报
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExClimbAppleTrees = channel.unary_unary(
                '/bilibili.gaia.gw.Gaia/ExClimbAppleTrees',
                request_serializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.GaiaEncryptMsgReq.SerializeToString,
                response_deserializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.UploadAppListReply.FromString,
                _registered_method=True)
        self.ExFetchPublicKey = channel.unary_unary(
                '/bilibili.gaia.gw.Gaia/ExFetchPublicKey',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.FetchPublicKeyReply.FromString,
                _registered_method=True)
        self.ExGetAxe = channel.unary_unary(
                '/bilibili.gaia.gw.Gaia/ExGetAxe',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.FetchPublicKeyReply.FromString,
                _registered_method=True)
        self.ExUploadAppList = channel.unary_unary(
                '/bilibili.gaia.gw.Gaia/ExUploadAppList',
                request_serializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.GaiaEncryptMsgReq.SerializeToString,
                response_deserializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.UploadAppListReply.FromString,
                _registered_method=True)


class GaiaServicer:
    """应用列表上报
    """

    def ExClimbAppleTrees(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExFetchPublicKey(self, request, context):
        """拉取rsa公钥
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExGetAxe(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExUploadAppList(self, request, context):
        """应用列表上报
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GaiaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExClimbAppleTrees': grpc.unary_unary_rpc_method_handler(
                    servicer.ExClimbAppleTrees,
                    request_deserializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.GaiaEncryptMsgReq.FromString,
                    response_serializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.UploadAppListReply.SerializeToString,
            ),
            'ExFetchPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ExFetchPublicKey,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.FetchPublicKeyReply.SerializeToString,
            ),
            'ExGetAxe': grpc.unary_unary_rpc_method_handler(
                    servicer.ExGetAxe,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.FetchPublicKeyReply.SerializeToString,
            ),
            'ExUploadAppList': grpc.unary_unary_rpc_method_handler(
                    servicer.ExUploadAppList,
                    request_deserializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.GaiaEncryptMsgReq.FromString,
                    response_serializer=bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.UploadAppListReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.gaia.gw.Gaia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilibili.gaia.gw.Gaia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gaia:
    """应用列表上报
    """

    @staticmethod
    def ExClimbAppleTrees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.gaia.gw.Gaia/ExClimbAppleTrees',
            bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.GaiaEncryptMsgReq.SerializeToString,
            bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.UploadAppListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExFetchPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.gaia.gw.Gaia/ExFetchPublicKey',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.FetchPublicKeyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExGetAxe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.gaia.gw.Gaia/ExGetAxe',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.FetchPublicKeyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExUploadAppList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.gaia.gw.Gaia/ExUploadAppList',
            bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.GaiaEncryptMsgReq.SerializeToString,
            bilibili_dot_gaia_dot_gw_dot_gw__api__pb2.UploadAppListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
