"""init base stamp

Revision ID: 285e2184fcda
Revises: 
Create Date: 2026-07-07 14:55:39.966870

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '285e2184fcda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_traffic_card', 'my_activity_status',
               existing_type=mysql.SMALLINT(),
               server_default=sa.text("'0'"),
               existing_comment='0：未查询活动\r\n1：已成功查询\r\n2：查询了，但获取到的活动为空，也就是未知的活动\r\n3：查询出错了，去日志里查原因',
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_traffic_card', 'my_activity_status',
               existing_type=mysql.SMALLINT(),
               server_default=sa.text("'0'"),
               existing_comment='0：未查询活动\r\n1：已成功查询\r\n2：查询了，但获取到的活动为空，也就是未知的活动\r\n3：查询出错了，去日志里查原因',
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
