"""first upgrade

Revision ID: 6993fdcfe4dc
Revises: 285e2184fcda
Create Date: 2026-07-07 15:43:21.724758

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '6993fdcfe4dc'
down_revision: Union[str, None] = '285e2184fcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除依赖旧索引的外键约束，再删除旧索引，然后创建新索引和外键
    op.drop_constraint('FK_era_jika_t_traffic_card', 't_era_jika', type_='foreignkey')
    op.drop_index(op.f('idx_traffic_card_id'), table_name='t_era_jika')
    op.create_index('FK_era_jika_t_traffic_card', 't_era_jika', ['traffic_card_id'], unique=False)
    op.create_foreign_key('FK_era_jika_t_traffic_card', 't_era_jika', 't_traffic_card', ['traffic_card_id'], ['id'])
    op.alter_column('t_topic', 'update_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('t_traffic_card', 'my_activity_status',
               existing_type=mysql.SMALLINT(),
               server_default=None,
               existing_comment='0：未查询活动\r\n1：已成功查询\r\n2：查询了，但获取到的活动为空，也就是未知的活动\r\n3：查询出错了，去日志里查原因',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_traffic_card', 'my_activity_status',
               existing_type=mysql.SMALLINT(),
               server_default=sa.text("'0'"),
               existing_comment='0：未查询活动\r\n1：已成功查询\r\n2：查询了，但获取到的活动为空，也就是未知的活动\r\n3：查询出错了，去日志里查原因',
               existing_nullable=True)
    op.alter_column('t_topic', 'update_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # 回退：先删除外键和新索引，再创建旧索引和外键
    op.drop_constraint('FK_era_jika_t_traffic_card', 't_era_jika', type_='foreignkey')
    op.drop_index('FK_era_jika_t_traffic_card', table_name='t_era_jika')
    op.create_index(op.f('idx_traffic_card_id'), 't_era_jika', ['traffic_card_id'], unique=False)
    op.create_foreign_key('FK_era_jika_t_traffic_card', 't_era_jika', 't_traffic_card', ['traffic_card_id'], ['id'])
    # ### end Alembic commands ###
