# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/vas/garb/service/card.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bilibili/vas/garb/service/card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bilibili.vas.garb.model import sailing_pb2 as bilibili_dot_vas_dot_garb_dot_model_dot_sailing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$bilibili/vas/garb/service/card.proto\x12\x19\x62ilibili.vas.garb.service\x1a%bilibili/vas/garb/model/sailing.proto\"\xb3\x02\n\x08UserCard\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07item_id\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61rd_url\x18\x04 \x01(\t\x12\x14\n\x0c\x62ig_card_url\x18\x05 \x01(\t\x12\x11\n\tcard_type\x18\x06 \x01(\x03\x12\x13\n\x0b\x65xpire_time\x18\x07 \x01(\x03\x12\x16\n\x0e\x63\x61rd_type_name\x18\x08 \x01(\t\x12\x10\n\x08jump_url\x18\t \x01(\t\x12\x31\n\x03\x66\x61n\x18\n \x01(\x0b\x32$.bilibili.vas.garb.model.UserFanShow\x12\x15\n\rimage_enhance\x18\x0c \x01(\t\x12\x38\n\x0bimage_group\x18\r \x01(\x0b\x32#.bilibili.vas.garb.model.ImageGroupB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.vas.garb.service.card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_USERCARD']._serialized_start=107
  _globals['_USERCARD']._serialized_end=414
# @@protoc_insertion_point(module_scope)
