"""init base stamp

Revision ID: 6b418fc97eb5
Revises: 
Create Date: 2026-07-07 14:56:50.112332

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '6b418fc97eb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_task_progress', 'last_page_num',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('crawl_task_progress', 'is_finished',
               existing_type=mysql.TINYINT(),
               server_default=sa.text("'0'"),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_task_progress', 'is_finished',
               existing_type=mysql.TINYINT(),
               server_default=sa.text("'0'"),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('crawl_task_progress', 'last_page_num',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
