# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bilibili.app.click.v1 import heartbeat_pb2 as bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2

GRPC_GENERATED_VERSION = '1.82.0rc2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bilibili/app/click/v1/heartbeat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClickStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HeartBeat = channel.unary_unary(
                '/bilibili.app.click.v1.Click/HeartBeat',
                request_serializer=bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2.HeartBeatReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2.HeartBeatReply.FromString,
                _registered_method=True)


class ClickServicer:
    """Missing associated documentation comment in .proto file."""

    def HeartBeat(self, request, context):
        """客户端心跳上传
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClickServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2.HeartBeatReq.FromString,
                    response_serializer=bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2.HeartBeatReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.app.click.v1.Click', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilibili.app.click.v1.Click', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Click:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.click.v1.Click/HeartBeat',
            bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2.HeartBeatReq.SerializeToString,
            bilibili_dot_app_dot_click_dot_v1_dot_heartbeat__pb2.HeartBeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
