# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/app/playerunite/pugvanymodel.proto/pugvanymodel.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'bilibili/app/playerunite/pugvanymodel.proto/pugvanymodel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>bilibili/app/playerunite/pugvanymodel.proto/pugvanymodel.proto\x12%bilibili.app.playerunite.pugvanymodel\";\n\nPlayerMask\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\x0e\n\x06suffix\x18\x03 \x01(\t\"\x8d\x02\n\x0cPUGVAnyModel\x12\x11\n\tseason_id\x18\x01 \x01(\x03\x12\x12\n\nepisode_id\x18\x02 \x01(\x03\x12\x44\n\x06status\x18\x03 \x01(\x0e\x32\x34.bilibili.app.playerunite.pugvanymodel.EpisodeStatus\x12H\n\x0crisk_control\x18\x04 \x01(\x0b\x32\x32.bilibili.app.playerunite.pugvanymodel.RiskControl\x12\x46\n\x0bplayer_mask\x18\x05 \x01(\x0b\x32\x31.bilibili.app.playerunite.pugvanymodel.PlayerMask\"\x83\x01\n\x0bRiskControl\x12\x15\n\rneed_send_sms\x18\x01 \x01(\x08\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0crisk_message\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63tion_desc\x18\x04 \x01(\t\x12\x14\n\x0csend_sms_url\x18\x05 \x01(\t\x12\r\n\x05\x62uvid\x18\x06 \x01(\t*\x9d\x01\n\rEpisodeStatus\x12\x1e\n\x1a\x45PISODE_STATUS_UNSPECIFIED\x10\x00\x12\"\n\x1e\x45PISODE_STATUS_TRY_WATCH_WHOLE\x10\x01\x12 \n\x1c\x45PISODE_STATUS_NOT_TRY_WATCH\x10\x02\x12&\n\"EPISODE_STATUS_TRY_WATCH_5_MINUTES\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.app.playerunite.pugvanymodel.proto.pugvanymodel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EPISODESTATUS']._serialized_start=573
  _globals['_EPISODESTATUS']._serialized_end=730
  _globals['_PLAYERMASK']._serialized_start=105
  _globals['_PLAYERMASK']._serialized_end=164
  _globals['_PUGVANYMODEL']._serialized_start=167
  _globals['_PUGVANYMODEL']._serialized_end=436
  _globals['_RISKCONTROL']._serialized_start=439
  _globals['_RISKCONTROL']._serialized_end=570
# @@protoc_insertion_point(module_scope)
