# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bilibili.app.viewunite.v1 import viewunite_pb2 as bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2

GRPC_GENERATED_VERSION = '1.82.0rc2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bilibili/app/viewunite/v1/viewunite_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ViewStub:
    """统一视频信息接口 (7.41.0+)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ArcRefresh = channel.unary_unary(
                '/bilibili.app.viewunite.v1.View/ArcRefresh',
                request_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ArcRefreshReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ArcRefreshReply.FromString,
                _registered_method=True)
        self.RelatesFeed = channel.unary_unary(
                '/bilibili.app.viewunite.v1.View/RelatesFeed',
                request_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.RelatesFeedReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.RelatesFeedReply.FromString,
                _registered_method=True)
        self.View = channel.unary_unary(
                '/bilibili.app.viewunite.v1.View/View',
                request_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewReply.FromString,
                _registered_method=True)
        self.ViewProgress = channel.unary_unary(
                '/bilibili.app.viewunite.v1.View/ViewProgress',
                request_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewProgressReq.SerializeToString,
                response_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewProgressReply.FromString,
                _registered_method=True)


class ViewServicer:
    """统一视频信息接口 (7.41.0+)
    """

    def ArcRefresh(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RelatesFeed(self, request, context):
        """视频详情页下方推荐
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def View(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewProgress(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ArcRefresh': grpc.unary_unary_rpc_method_handler(
                    servicer.ArcRefresh,
                    request_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ArcRefreshReq.FromString,
                    response_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ArcRefreshReply.SerializeToString,
            ),
            'RelatesFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.RelatesFeed,
                    request_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.RelatesFeedReq.FromString,
                    response_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.RelatesFeedReply.SerializeToString,
            ),
            'View': grpc.unary_unary_rpc_method_handler(
                    servicer.View,
                    request_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewReq.FromString,
                    response_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewReply.SerializeToString,
            ),
            'ViewProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewProgress,
                    request_deserializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewProgressReq.FromString,
                    response_serializer=bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewProgressReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.app.viewunite.v1.View', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilibili.app.viewunite.v1.View', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class View:
    """统一视频信息接口 (7.41.0+)
    """

    @staticmethod
    def ArcRefresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.viewunite.v1.View/ArcRefresh',
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ArcRefreshReq.SerializeToString,
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ArcRefreshReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RelatesFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.viewunite.v1.View/RelatesFeed',
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.RelatesFeedReq.SerializeToString,
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.RelatesFeedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def View(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.viewunite.v1.View/View',
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewReq.SerializeToString,
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.app.viewunite.v1.View/ViewProgress',
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewProgressReq.SerializeToString,
            bilibili_dot_app_dot_viewunite_dot_v1_dot_viewunite__pb2.ViewProgressReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
