# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/app/feed/v1/feed.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bilibili/app/feed/v1/feed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62ilibili/app/feed/v1/feed.proto\x12\x14\x62ilibili.app.feed.v1\"y\n\x07QoeForm\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x30\n\x07options\x18\x02 \x03(\x0b\x32\x1f.bilibili.app.feed.v1.QoeOption\x12\x18\n\x10has_second_layer\x18\x03 \x01(\x08\x12\x14\n\x0c\x63onfirm_text\x18\x04 \x01(\t\"K\n\tQoeOption\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x65sc\x18\x03 \x03(\t\x12\x12\n\ndesc_title\x18\x04 \x01(\t\"7\n\x06QoeReq\x12\x10\n\x08qoe_info\x18\x01 \x01(\t\x12\x0b\n\x03oid\x18\x02 \x01(\x03\x12\x0e\n\x06up_mid\x18\x03 \x01(\x03\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.app.feed.v1.feed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_QOEFORM']._serialized_start=57
  _globals['_QOEFORM']._serialized_end=178
  _globals['_QOEOPTION']._serialized_start=180
  _globals['_QOEOPTION']._serialized_end=255
  _globals['_QOEREQ']._serialized_start=257
  _globals['_QOEREQ']._serialized_end=312
# @@protoc_insertion_point(module_scope)
