# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bilibili.im.interfaces.inner_interface.v1 import api_pb2 as bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2

GRPC_GENERATED_VERSION = '1.82.0rc2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bilibili/im/interfaces/inner_interface/v1/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InnerInterfaceStub:
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateListInn = channel.unary_unary(
                '/bilibili.im.interface.inner.interface.v1.InnerInterface/UpdateListInn',
                request_serializer=bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2.ReqOpBlacklist.SerializeToString,
                response_deserializer=bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2.RspOpBlacklist.FromString,
                _registered_method=True)


class InnerInterfaceServicer:
    """
    """

    def UpdateListInn(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InnerInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateListInn': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateListInn,
                    request_deserializer=bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2.ReqOpBlacklist.FromString,
                    response_serializer=bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2.RspOpBlacklist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.im.interface.inner.interface.v1.InnerInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilibili.im.interface.inner.interface.v1.InnerInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InnerInterface:
    """
    """

    @staticmethod
    def UpdateListInn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.im.interface.inner.interface.v1.InnerInterface/UpdateListInn',
            bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2.ReqOpBlacklist.SerializeToString,
            bilibili_dot_im_dot_interfaces_dot_inner__interface_dot_v1_dot_api__pb2.RspOpBlacklist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
