# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/app/growth/v1/growth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bilibili/app/growth/v1/growth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#bilibili/app/growth/v1/growth.proto\x12\x16\x62ilibili.app.growth.v1\"z\n\x0c\x41\x64\x44\x65viceInfo\x12\x0c\n\x04imei\x18\x01 \x01(\t\x12\x10\n\x08imei_md5\x18\x02 \x01(\t\x12\x0c\n\x04oaid\x18\x03 \x01(\t\x12\x10\n\x08oaid_md5\x18\x04 \x01(\t\x12\x12\n\nandroid_id\x18\x05 \x01(\t\x12\x16\n\x0e\x61ndroid_id_md5\x18\x06 \x01(\t\"\xc4\x01\n\x14ReportAttributionReq\x12<\n\x0e\x61\x64_device_info\x18\x01 \x01(\x0b\x32$.bilibili.app.growth.v1.AdDeviceInfo\x12\x18\n\x10\x61ttribution_data\x18\x02 \x01(\t\x12\x12\n\nclick_time\x18\x03 \x01(\x03\x12\x15\n\rdownload_time\x18\x04 \x01(\x03\x12\x14\n\x0cinstall_time\x18\x05 \x01(\x03\x12\x13\n\x0breferrer_ex\x18\x06 \x01(\t\"\x17\n\x15ReportAttributionRespB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.app.growth.v1.growth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_ADDEVICEINFO']._serialized_start=63
  _globals['_ADDEVICEINFO']._serialized_end=185
  _globals['_REPORTATTRIBUTIONREQ']._serialized_start=188
  _globals['_REPORTATTRIBUTIONREQ']._serialized_end=384
  _globals['_REPORTATTRIBUTIONRESP']._serialized_start=386
  _globals['_REPORTATTRIBUTIONRESP']._serialized_end=409
# @@protoc_insertion_point(module_scope)
