netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:f::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:f::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:e::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:e::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:d::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:d::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:c::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:c::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:b::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:b::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:a::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:a::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:9::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:9::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:8::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:8::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:7::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:7::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:6::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:6::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:5::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:5::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:4::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:4::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:3::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:3::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:2::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:2::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:1::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}:1::b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}::1b
netsh interface ipv6 add address {net_adapter_name} {ipv6_prefix}::b
