# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bilibili.community.service.govern.v1 import govern_pb2 as bilibili_dot_community_dot_service_dot_govern_dot_v1_dot_govern__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.82.0rc2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bilibili/community/service/govern/v1/govern_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QoeStub:
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QoeReport = channel.unary_unary(
                '/bilibili.community.service.govern.v1.Qoe/QoeReport',
                request_serializer=bilibili_dot_community_dot_service_dot_govern_dot_v1_dot_govern__pb2.QoeReportReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class QoeServicer:
    """
    """

    def QoeReport(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QoeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QoeReport': grpc.unary_unary_rpc_method_handler(
                    servicer.QoeReport,
                    request_deserializer=bilibili_dot_community_dot_service_dot_govern_dot_v1_dot_govern__pb2.QoeReportReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.community.service.govern.v1.Qoe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilibili.community.service.govern.v1.Qoe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Qoe:
    """
    """

    @staticmethod
    def QoeReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilibili.community.service.govern.v1.Qoe/QoeReport',
            bilibili_dot_community_dot_service_dot_govern_dot_v1_dot_govern__pb2.QoeReportReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
